In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib widget
%pwd

'/projectnb/batmanlab/mragoza/lung-project/notebooks/copdgene'

In [2]:
import sys, os

def add_path(p: str):
    if p not in sys.path:
        sys.path.append(p)

add_path(os.environ['LP_ROOT'])
import project

add_path(os.environ['PROJECT'] + '/' + 'param_search')
import param_search as ps

ps.set_backend('sge')
ps.set_verbose(False)

# Gather examples

In [3]:
from pathlib import Path
#data_root = Path(os.environ['LP_ROOT'] / 'data' / 'COPDGene'
data_root = Path(os.environ['PRIVATE']) / 'data' / 'COPDGene'
data_root.is_dir()

True

In [4]:
import pandas as pd
subject_file = data_root / 'sample1000_2025-07-22.csv'
subject_list = list(pd.read_csv(subject_file, sep='\t').sid)
len(subject_list)

1000

# Setup experiment

In [5]:
base_dir = '2026-09-15_preprocess'

template = '''\
#!/bin/bash -l
#$ -N {job_name}
#$ -P batmanlab
#$ -pe omp 4
#$ -l gpus=1
#$ -l gpu_memory=16G
#$ -l h_rt=3:00:00
set -eo pipefail

mamba activate $PROJECT/mambaforge/envs/warp

export PYTHONPATH=$LP_ROOT:$PROJECT:$PYTHOPATH

python $LP_ROOT/scripts/preprocess.py {config} \\
    --set dataset.subjects=[{subject}] \\
    --set dataset.variant={variant} \\
    --set dataset.pipeline_tags.forward_simulation={fwd_tag} \\
    --set preprocessing.forward_simulation.pde_solver.material_type={mat_type}

'''
name_format = 'job_{params_hash}'

grid = ps.param_grid(
    config='2026-09-15_config.yaml',
    subject=subject_list,
    variant='2026-09-15',
    fwd_tag='LE',
    mat_type='linear'
)

len(grid)

1000

In [6]:
jobs = ps.setup(base_dir, template, name_format, grid, overwrite=True)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,log_dir,stdout_path,stderr_path,params_json,params_hash,params.config,params.subject,params.variant,params.fwd_tag,params.mat_type
0,job_dff3f5b4c40b66ce,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,/projectnb/batmanlab/mragoza/lung-project/note...,<NA>,<NA>,"{""config"": ""2026-09-15_config.yaml"", ""fwd_tag""...",dff3f5b4c40b66ce,/projectnb/batmanlab/mragoza/lung-project/note...,16514P,2026-09-15,LE,linear
1,job_31be35a7a76de560,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,/projectnb/batmanlab/mragoza/lung-project/note...,<NA>,<NA>,"{""config"": ""2026-09-15_config.yaml"", ""fwd_tag""...",31be35a7a76de560,/projectnb/batmanlab/mragoza/lung-project/note...,20748Q,2026-09-15,LE,linear
2,job_e0ce5aae5fcc604f,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,/projectnb/batmanlab/mragoza/lung-project/note...,<NA>,<NA>,"{""config"": ""2026-09-15_config.yaml"", ""fwd_tag""...",e0ce5aae5fcc604f,/projectnb/batmanlab/mragoza/lung-project/note...,11007Z,2026-09-15,LE,linear
3,job_63f85f291aaa8ce6,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,/projectnb/batmanlab/mragoza/lung-project/note...,<NA>,<NA>,"{""config"": ""2026-09-15_config.yaml"", ""fwd_tag""...",63f85f291aaa8ce6,/projectnb/batmanlab/mragoza/lung-project/note...,14771Z,2026-09-15,LE,linear
4,job_98d44af8ed9a7c8e,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,/projectnb/batmanlab/mragoza/lung-project/note...,<NA>,<NA>,"{""config"": ""2026-09-15_config.yaml"", ""fwd_tag""...",98d44af8ed9a7c8e,/projectnb/batmanlab/mragoza/lung-project/note...,13651K,2026-09-15,LE,linear
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job_664e21ade655d01d,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,/projectnb/batmanlab/mragoza/lung-project/note...,<NA>,<NA>,"{""config"": ""2026-09-15_config.yaml"", ""fwd_tag""...",664e21ade655d01d,/projectnb/batmanlab/mragoza/lung-project/note...,20519B,2026-09-15,LE,linear
996,job_8c8f24c657c51935,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,/projectnb/batmanlab/mragoza/lung-project/note...,<NA>,<NA>,"{""config"": ""2026-09-15_config.yaml"", ""fwd_tag""...",8c8f24c657c51935,/projectnb/batmanlab/mragoza/lung-project/note...,12294H,2026-09-15,LE,linear
997,job_0ad80fc533d333c8,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,/projectnb/batmanlab/mragoza/lung-project/note...,<NA>,<NA>,"{""config"": ""2026-09-15_config.yaml"", ""fwd_tag""...",0ad80fc533d333c8,/projectnb/batmanlab/mragoza/lung-project/note...,23123R,2026-09-15,LE,linear
998,job_137c03d7e44152a3,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,/projectnb/batmanlab/mragoza/lung-project/note...,<NA>,<NA>,"{""config"": ""2026-09-15_config.yaml"", ""fwd_tag""...",137c03d7e44152a3,/projectnb/batmanlab/mragoza/lung-project/note...,16546C,2026-09-15,LE,linear
999,job_6d8af03ac425e6d6,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,/projectnb/batmanlab/mragoza/lung-project/note...,<NA>,<NA>,"{""config"": ""2026-09-15_config.yaml"", ""fwd_tag""...",6d8af03ac425e6d6,/projectnb/batmanlab/mragoza/lung-project/note...,11099E,2026-09-15,LE,linear

In [7]:
jobs = ps.load(base_dir)

In [7]:
jobs = ps.submit(jobs)

In [8]:
%autoreload
jobs = ps.recover(jobs)
jobs = ps.status(jobs)
jobs = ps.history(jobs) # TODO not working for SGE backend; stale job_states
jobs = ps.collect(jobs)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.fwd_tag,params.mat_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime
0,job_dff3f5b4c40b66ce,RUNNING,1,7581512,scc-307,00:00:49,| ├── 'material_type': 'linear'\n | ...,"preprocessing.preprocess_example(ex, confi...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,LE,linear,NaN,2026-09-15T13:02:39,status,NaN,NaN,False,<NA>,<NA>
1,job_31be35a7a76de560,RUNNING,1,7581513,scc-307,00:00:49,| ├── 'material_type': 'linear'\n | ...,"preprocessing.preprocess_example(ex, confi...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,LE,linear,NaN,2026-09-15T13:02:39,status,NaN,NaN,False,<NA>,<NA>
2,job_e0ce5aae5fcc604f,RUNNING,1,7581514,scc-307,00:00:49,| ├── 'material_type': 'linear'\n | ...,"preprocessing.preprocess_example(ex, confi...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,LE,linear,NaN,2026-09-15T13:02:39,status,NaN,NaN,False,<NA>,<NA>
3,job_63f85f291aaa8ce6,RUNNING,1,7581515,scc-k02,00:00:49,If you use this tool please cite: https://pubs...,"\r 0%| | 0/1 [00:00<?, ?it/s]\r100%|...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,LE,linear,NaN,2026-09-15T13:02:39,status,NaN,NaN,False,<NA>,<NA>
4,job_98d44af8ed9a7c8e,RUNNING,1,7581516,scc-k02,00:00:49,| ├── 'material_type': 'linear'\n | ...,"preprocessing.preprocess_example(ex, confi...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,LE,linear,NaN,2026-09-15T13:02:39,status,NaN,NaN,False,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job_664e21ade655d01d,PENDING,1,7582536,None,None,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,LE,linear,NaN,2026-09-15T13:02:39,status,NaN,NaN,False,<NA>,<NA>
996,job_8c8f24c657c51935,PENDING,1,7582537,None,None,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,LE,linear,NaN,2026-09-15T13:02:39,status,NaN,NaN,False,<NA>,<NA>
997,job_0ad80fc533d333c8,PENDING,1,7582538,None,None,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,LE,linear,NaN,2026-09-15T13:02:39,status,NaN,NaN,False,<NA>,<NA>
998,job_137c03d7e44152a3,PENDING,1,7582539,None,None,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,LE,linear,NaN,2026-09-15T13:02:39,status,NaN,NaN,False,<NA>,<NA>
999,job_6d8af03ac425e6d6,PENDING,1,7582540,None,None,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,LE,linear,NaN,2026-09-15T13:02:39,status,NaN,NaN,False,<NA>,<NA>

In [9]:
jobs.groupby('job_state').count()

,job_name,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,script_path,...,params.fwd_tag,params.mat_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime
job_state,,,,,,,,,,,,,,,,,,,,,
PENDING,961,961,961,0,0,961,961,961,961,961,...,961,961,0,961,961,0,0,961,0,0
RUNNING,9,9,9,9,9,9,9,9,9,9,...,9,9,0,9,9,0,0,9,0,0
SUBMITTED,30,30,30,0,0,30,30,30,30,30,...,30,30,0,0,0,0,0,30,0,0

In [28]:
def classify_error(stderr):
    if pd.isnull(stderr):
        return 'No stderr file'
    elif not str(stderr).strip():
        return 'No error message'
    elif 'CUDA out of memory' in stderr or ('Failed to allocate' in stderr and "bytes on device 'cuda" in stderr):
        return 'GPU out of memory'
    elif 'Non-positive density' in stderr:
        return 'Non-positive density'
    elif 'construct initial points' in stderr or 'Exuding' in stderr or ('Moving #' in stderr and 'addr:' in stderr):
        return 'pygalmesh output'
    elif 'FileNotFoundError' in stderr and 'network_weights' in stderr:
        return  'Weights not found'
    return 'Uncategorized error'

jobs['error_type'] = jobs.stderr.map(classify_error)
jobs.groupby('error_type')[['job_name']].count()

                     job_name
error_type
GPU out of memory         224
Uncategorized error         1
Weights not found         775

In [35]:
error_type = 'Weights not found'
print(jobs[jobs.error_type == error_type].iloc[0])
print(jobs[jobs.error_type == error_type].iloc[0].stderr)

job_name                                        job_dff3f5b4c40b66ce
job_state                                                  SUBMITTED
n_submits                                                          1
job_id                                                       7578213
node_id                                                         None
runtime                                                         None
stdout             [chkpt] /restricted/projectnb/batmanlab/haozhe...
stderr                 return True, func(*args, **kwargs)\n      ...
base_dir           /projectnb/batmanlab/mragoza/lung-project/note...
work_dir           /projectnb/batmanlab/mragoza/lung-project/note...
script_path        /projectnb/batmanlab/mragoza/lung-project/note...
output_path        /projectnb/batmanlab/mragoza/lung-project/note...
log_dir            /projectnb/batmanlab/mragoza/lung-project/note...
stdout_path        /projectnb/batmanlab/mragoza/lung-project/note...
stderr_path        /projectnb/batmanlab/mragoza/lung-project/note...
params_json        {"config": "2026-09-15_config.yaml", "fwd_tag"...
params_hash                                         dff3f5b4c40b66ce
params.config      /projectnb/batmanlab/mragoza/lung-project/note...
params.subject                                                16514P
params.variant                                            2026-09-15
params.fwd_tag                                                    LE
params.mat_type                                               linear
array_idx                                                        NaN
last_live_at                                                    None
state_source                                                    None
finalized                                                       None
finalized_at                                                    None
output_exists                                                  False
output_fsize                                                    <NA>
output_mtime                                                    <NA>
error_type                                         Weights not found
Name: 0, dtype: object
    return True, func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/lung-project/project/preprocessing/stages.py", line 131, in estimate_displacement_field
    image_registration.run_image_registration(
  File "/projectnb/batmanlab/mragoza/lung-project/project/preprocessing/operations/image_registration.py", line 66, in run_image_registration
    return run_unigradicon_registration(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/lung-project/project/preprocessing/operations/image_registration.py", line 104, in run_unigradicon_registration
    run_unigradicon_main(
  File "/projectnb/batmanlab/mragoza/lung-project/project/preprocessing/operations/image_registration.py", line 146, in run_unigradicon_main
    net = unigradicon.get_model_from_model_zoo(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/mambaforge/envs/warp/lib/python3.11/site-packages/unigradicon/__init__.py", line 711, in get_model_from_model_zoo
    return get_gradicon_lung(loss_fn, apply_intensity_conservation_loss, use_intersection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/mambaforge/envs/warp/lib/python3.11/site-packages/unigradicon/__init__.py", line 695, in get_gradicon_lung
    os.makedirs("network_weights/gradicon_lung1.0/", exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: 'network_weights/gradicon_lung1.0/'

In [33]:
import yaml
yaml.safe_load('a: 1.e-5')

{'a': 1e-05}

In [25]:
jobs.loc[:, 'job_id'] = pd.NA

In [28]:
%autoreload
jobs = ps.submit(jobs)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params_json,params_hash,params.config,params.data_name,params.data_root,params.subject,params.mat_tag,params.fwd_tag,params.mat_type,params.variant
0,jobead9ab1e5bc03c66,SUBMITTED,1,7159234,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",ead9ab1e5bc03c66,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,16514P,bela,linear,linear,2026-08-08
1,job96ef0272ef81ee7e,SUBMITTED,1,7159235,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",96ef0272ef81ee7e,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,20748Q,bela,linear,linear,2026-08-08
2,job4d5d759871906077,SUBMITTED,1,7159236,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",4d5d759871906077,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,11007Z,bela,linear,linear,2026-08-08
3,job62c1bdeb21500ce0,SUBMITTED,1,7159237,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",62c1bdeb21500ce0,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,14771Z,bela,linear,linear,2026-08-08
4,job1a856f1cecae8f51,SUBMITTED,1,7159238,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",1a856f1cecae8f51,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,13651K,bela,linear,linear,2026-08-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job22f2adacb02a421c,SUBMITTED,1,7160229,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",22f2adacb02a421c,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,20519B,bela,linear,linear,2026-08-08
996,jobb1e67f498dc392b6,SUBMITTED,1,7160230,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",b1e67f498dc392b6,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,12294H,bela,linear,linear,2026-08-08
997,job2f617f39d23060c8,SUBMITTED,1,7160231,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",2f617f39d23060c8,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,23123R,bela,linear,linear,2026-08-08
998,jobbef061b64dfcfc4e,SUBMITTED,1,7160232,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",bef061b64dfcfc4e,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,16546C,bela,linear,linear,2026-08-08
999,job2ee27f6ba5ec4ec2,SUBMITTED,1,7160233,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",2ee27f6ba5ec4ec2,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,11099E,bela,linear,linear,2026-08-08