In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib widget
%pwd

'/projectnb/batmanlab/mragoza/lung-project/notebooks/copdgene'

In [2]:
import sys, os
import pandas as pd

sys.path.append(os.environ['LP_ROOT'])
import project

sys.path.append(os.environ['PROJECT'] + '/param_search')
import param_search as ps

ps.set_backend('sge')
ps.set_verbose(False)

# Gather examples

In [3]:
from pathlib import Path
#data_root = Path(os.environ['LP_ROOT'] / 'data' / 'COPDGene'
data_root = Path(os.environ['PRIVATE']) / 'data' / 'COPDGene'
for p in data_root.iterdir():
    print(p)

/restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/sample1000_2025-07-22.txt
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/sample1000_2025-07-22.csv
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/subject_files.txt
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/Images
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/sample1000_2025-07-17.csv
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/DISK_USAGE
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/ClinicalData

In [4]:
subject_file = data_root / 'sample1000_2025-07-22.csv'
subject_list = list(pd.read_csv(subject_file, sep='\t').sid)
subject_list

['16514P',
 '20748Q',
 '11007Z',
 '14771Z',
 '13651K',
 '15900P',
 '15312Y',
 '21042H',
 '21877G',
 '10127E',
 '23577E',
 '13816Q',
 '21559S',
 '25335Q',
 '23023N',
 '10572Z',
 '10887Y',
 '21410K',
 '17920F',
 '14684E',
 '16132B',
 '17862R',
 '11746L',
 '25728J',
 '20609C',
 '16637F',
 '13297S',
 '25767T',
 '25695U',
 '21572K',
 '15078Q',
 '15297C',
 '14857J',
 '13460D',
 '18840M',
 '12506W',
 '11498S',
 '21611U',
 '15088T',
 '12831H',
 '19612E',
 '19784H',
 '10217F',
 '23037Y',
 '25130Y',
 '15623P',
 '19027T',
 '14380K',
 '10212V',
 '16060C',
 '19356M',
 '22357L',
 '25923H',
 '21189L',
 '24608U',
 '15204V',
 '11743F',
 '11879E',
 '12477P',
 '10815Z',
 '17790S',
 '15489L',
 '11850G',
 '13034M',
 '17255W',
 '14632L',
 '26066U',
 '18184E',
 '15532M',
 '19558Y',
 '20640W',
 '21741H',
 '18015H',
 '17137Q',
 '12422Q',
 '15699W',
 '21933Q',
 '18397V',
 '14550J',
 '20703U',
 '21004Z',
 '24581A',
 '24331D',
 '17505T',
 '15894U',
 '16977D',
 '18935X',
 '19410S',
 '18515B',
 '21399W',
 '21899Q',
 '16091N',
 '17617E',
 '23574Y',
 '11943N',
 '12962W',
 '17104B',
 '20064M',
 '16605S',
 '13170U',
 '24954N',
 '20400C',
 '24682G',
 '24012N',
 '25888F',
 '21052K',
 '20696X',
 '17385J',
 '21223L',
 '13916U',
 '14633N',
 '16021S',
 '18801C',
 '20981W',
 '19819A',
 '21521T',
 '11193W',
 '17939A',
 '18153T',
 '24271L',
 '14217Z',
 '15424J',
 '24514L',
 '21892C',
 '23239K',
 '21083V',
 '17233M',
 '10539B',
 '19091C',
 '10560S',
 '25410E',
 '18798N',
 '25601L',
 '18434B',
 '19627R',
 '16347W',
 '12676V',
 '16853L',
 '24973R',
 '13084B',
 '15163H',
 '24711N',
 '11235M',
 '21587X',
 '13071S',
 '25096Y',
 '23725T',
 '19324Z',
 '21813G',
 '26112B',
 '11350M',
 '14084G',
 '22873D',
 '15827F',
 '19880D',
 '13845X',
 '13264D',
 '18629Q',
 '20024A',
 '12651F',
 '18687E',
 '21168D',
 '11198G',
 '11783R',
 '25674M',
 '10332F',
 '20385G',
 '20088A',
 '20623W',
 '25407P',
 '23930U',
 '15473W',
 '19922T',
 '20453X',
 '19478A',
 '24394B',
 '18761Q',
 '15650S',
 '14417H',
 '16823C',
 '21679C',
 '20678V',
 '17144N',
 '19849J',
 '20375D',
 '20770J',
 '14788Q',
 '17922J',
 '15549D',
 '15073G',
 '26004Y',
 '18830J',
 '25914G',
 '18317X',
 '24867S',
 '13350W',
 '19839G',
 '14332Z',
 '14157H',
 '17847V',
 '21176C',
 '25703T',
 '22855B',
 '11713W',
 '21175A',
 '14329K',
 '15350G',
 '13901H',
 '24744C',
 '25007Z',
 '17428B',
 '21469R',
 '25347X',
 '22224S',
 '15807Z',
 '14924Y',
 '25900V',
 '20005W',
 '25310A',
 '25125F',
 '14668G',
 '25311C',
 '14705M',
 '13282F',
 '10181K',
 '24873N',
 '18593V',
 '19549X',
 '21224N',
 '13998W',
 '12519F',
 '19396Y',
 '20149U',
 '16064K',
 '25894A',
 '22151R',
 '22135T',
 '13488Z',
 '23636U',
 '19637U',
 '20306K',
 '20412J',
 '16700M',
 '11947V',
 '19049D',
 '12825M',
 '19393S',
 '18374J',
 '10301U',
 '15072E',
 '24638D',
 '18714H',
 '14013J',
 '25950K',
 '19139E',
 '15911U',
 '13103F',
 '25072K',
 '13528L',
 '21106H',
 '15635W',
 '26071N',
 '23705N',
 '21769D',
 '15502D',
 '18126Q',
 '18940Q',
 '10736D',
 '20867Y',
 '15413E',
 '19024N',
 '17089F',
 '20668S',
 '19096M',
 '13728T',
 '10566E',
 '12418Z',
 '13255C',
 '22002A',
 '23136A',
 '23052U',
 '14704K',
 '17433U',
 '21163T',
 '16540Q',
 '21065T',
 '10947Q',
 '25552Y',
 '13370C',
 '19733Q',
 '16058P',
 '11721V',
 '19950Y',
 '23743V',
 '12812D',
 '10512H',
 '14646W',
 '13111E',
 '14113N',
 '12607C',
 '15272M',
 '17247X',
 '13358M',
 '22678F',
 '14845C',
 '10179X',
 '10524O',
 '22986Q',
 '22487Y',
 '13507D',
 '10367Y',
 '17011U',
 '22504Y',
 '19367R',
 '10432J',
 '14309E',
 '13719S',
 '10481W',
 '23940X',
 '20188E',
 '21837U',
 '10049K',
 '14729A',
 '10523M',
 '21484N',
 '23526N',
 '11972U',
 '20970R',
 '16402E',
 '13498C',
 '17557M',
 '16613R',
 '13340T',
 '13682V',
 '24576H',
 '15537W',
 '23091E',
 '18043M',
 '21615C',
 '11903B',
 '15898C',
 '10155J',
 '12139V',
 '20006Y',
 '19730K',
 '18682U',
 '26012X',
 '21886H',
 '11998M',
 '16537B',
 '22389Y',
 '20589W',
 '16675N',
 '19339M',
 '22308Y',
 '22827W',
 '10817D',
 '20195B',
 '10314D',
 '12052J',
 '14180C',
 '14905U',
 '21272Y',
 '18808Q',
 '12593R',
 '21604X',
 '11120V',
 '25120V',
 '13945B',
 '24113T',
 '18140K',
 '14293P',
 '22031H',
 '23741R',
 '22983K',
 '13301J',
 '14834X',
 '15319M',
 '16065M',
 '10663C',
 '11477K',
 '10709A',
 '24714T',
 '25694S',
 '14462M',
 '23558A',
 '22617L',
 '22182C',
 '13489B',
 '12478R',
 '15909H',
 '21765V',
 '16527Y',
 '23549Z',
 '11281T',
 '17836Q',
 '10502E',
 '13407Z',
 '15488J',
 '19560L',
 '11195A',
 '19415C',
 '23657C',
 '20659R',
 '18351X',
 '10646C',
 '24279B',
 '23155E',
 '16069U',
 '13273E',
 '10265Q',
 '19887R',
 '15040R',
 '21622Z',
 '16300W',
 '17995K',
 '11224H',
 '22092B',
 '10395D',
 '10124Y',
 '18677B',
 '16716B',
 '23284P',
 '11440N',
 '11085T',
 '11292Y',
 '20117H',
 '11255S',
 '14875L',
 '11613S',
 '16076R',
 '11226L',
 '11830A',
 '13242T',
 '12248A',
 '13248F',
 '14525K',
 '11716C',
 '22483Q',
 '15082H',
 '16472Z',
 '11752G',
 '22600U',
 '17722B',
 '25276A',
 '23686J',
 '22726Q',
 '22261Y',
 '20543Y',
 '11901X',
 '10233D',
 '10888A',
 '18563M',
 '22928C',
 '12223K',
 '11329V',
 '10908G',
 '13384N',
 '17102X',
 '14508K',
 '23011G',
 '25320D',
 '19594C',
 '10728E',
 '24646C',
 '25602N',
 '15152C',
 '22464M',
 '19679K',
 '24106W',
 '14075F',
 '10880K',
 '21614A',
 '10724W',
 '17629L',
 '25926N',
 '25403H',
 '21968J',
 '18982G',
 '24269Y',
 '24154H',
 '20977F',
 '14526M',
 '13799Q',
 '22667A',
 '22170V',
 '10705S',
 '24810P',
 '21438G',
 '10634V',
 '16216H',
 '15384X',
 '13925V',
 '17337Y',
 '12851N',
 '14261C',
 '21660H',
 '15232A',
 '25389N',
 '18525E',
 '19785J',
 '15165L',
 '14774F',
 '11750C',
 '20803Y',
 '23193M',
 '23656A',
 '18703C',
 '15934G',
 '19598K',
 '16440M',
 '16045G',
 '19783F',
 '10130T',
 '10261I',
 '18519J',
 '18452D',
 '21850M',
 '17955Y',
 '17473G',
 '15237K',
 '24449A',
 '11211Y',
 '24123W',
 '17173U',
 '24705S',
 '18274F',
 '11858W',
 '20566K',
 '20008C',
 '13341V',
 '18674V',
 '17897K',
 '10196X',
 '10973R',
 '15929N',
 '16747M',
 '15217E',
 '20296H',
 '11506R',
 '24447W',
 '16573F',
 '19666B',
 '17366F',
 '24383W',
 '24761C',
 '20976D',
 '22637R',
 '10842C',
 '14278T',
 '16277B',
 '11063J',
 '14683C',
 '24757L',
 '20901Y',
 '21419C',
 '22536L',
 '13533E',
 '23077K',
 '12861Q',
 '22113J',
 '11114A',
 '23746B',
 '19921R',
 '12903G',
 '15221V',
 '10056H',
 '22592V',
 '21170Q',
 '10564A',
 '23934C',
 '12683S',
 '14330V',
 '21384J',
 '11404J',
 '17573K',
 '24059N',
 '24950F',
 '14732P',
 '11005V',
 '10490X',
 '16294B',
 '22912N',
 '21153Q',
 '14201K',
 '20378J',
 '13053Q',
 '11468J',
 '19143V',
 '24887Y',
 '15905Z',
 '11616Y',
 '21538K',
 '21800X',
 '15450K',
 '23181F',
 '24064G',
 '21586V',
 '11676Q',
 '10153F',
 '24691H',
 '10227I',
 '19251Y',
 '11516U',
 '22116P',
 '23124T',
 '12339D',
 '21010U',
 '10919L',
 '14987W',
 '10213X',
 '25309P',
 '12878H',
 '21526D',
 '14121M',
 '11782P',
 '12362Y',
 '22597F',
 '15262J',
 '20592L',
 '12187G',
 '19056A',
 '13419G',
 '20286E',
 '14173F',
 '10829K',
 '11618C',
 '23094K',
 '17212E',
 '22253Z',
 '17904H',
 '12905K',
 '18278N',
 '24181K',
 '21293G',
 '23618S',
 '21778E',
 '11514Q',
 '10571X',
 '11545B',
 '21064R',
 '13736S',
 '13092A',
 '12231J',
 '22663S',
 '16266W',
 '20019H',
 '13428H',
 '13501R',
 '11363V',
 '23821P',
 '25303D',
 '19912Q',
 '12147U',
 '12146S',
 '17266B',
 '17894E',
 '18403Q',
 '24679R',
 '15799A',
 '11260L',
 '22114L',
 '10561U',
 '10990R',
 '12466K',
 '14031L',
 '25782P',
 '22759F',
 '21640B',
 '10568I',
 '23074E',
 '18103E',
 '11819M',
 '18341U',
 '18451B',
 '11512M',
 '10328O',
 '14863E',
 '18364G',
 '13149D',
 '15357U',
 '22566U',
 '11852K',
 '14047A',
 '21647P',
 '21508B',
 '13648V',
 '25380V',
 '11353S',
 '13578A',
 '23816W',
 '14837D',
 '22198R',
 '15840X',
 '14745Y',
 '20807G',
 '10761C',
 '11556G',
 '20622U',
 '11240F',
 '24137H',
 '25328T',
 '12608E',
 '11027F',
 '17509B',
 '23902P',
 '15661X',
 '22210H',
 '22193H',
 '25360P',
 '21595W',
 '15164J',
 '10843E',
 '25051C',
 '15527T',
 '22497B',
 '16142E',
 '21391G',
 '25991Y',
 '20632X',
 '17461Z',
 '10883Q',
 '14685G',
 '22604C',
 '21279M',
 '10567G',
 '10478H',
 '25231E',
 '24390T',
 '10641S',
 '19760T',
 '22495X',
 '13267J',
 '13354E',
 '15965R',
 '20151H',
 '10635X',
 '18845W',
 '24927K',
 '21012Y',
 '24205Y',
 '14240U',
 '22055V',
 '13093C',
 '23165H',
 '13365J',
 '24151B',
 '15156K',
 '15607R',
 '22946E',
 '16059R',
 '10081G',
 '20529E',
 '19913S',
 '23269T',
 '25835K',
 '22745U',
 '23266N',
 '18736R',
 '24830V',
 '22484S',
 '19579G',
 '14991N',
 '11325N',
 '21398U',
 '25205D',
 '18553J',
 '14374P',
 '12336X',
 '20435V',
 '23150U',
 '15848N',
 '23310Q',
 '23699S',
 '15606P',
 '14307A',
 '25245P',
 '11123B',
 '19686H',
 '11708D',
 '23252C',
 '14471N',
 '15885T',
 '23326F',
 '25003R',
 '10017X',
 '10426O',
 '22891F',
 '15745D',
 '20332L',
 '23803N',
 '24684K',
 '13530Y',
 '14386W',
 '24643W',
 '24350H',
 '18786G',
 '10458B',
 '14880E',
 '18505Y',
 '13864B',
 '11455A',
 '12795D',
 '25165R',
 '24562W',
 '14232V',
 '10975V',
 '15811Q',
 '23075G',
 '21556M',
 '23293Q',
 '22423Y',
 '19908Z',
 '21838W',
 '12630X',
 '22148C',
 '24186U',
 '25400B',
 '10624S',
 '25704V',
 '21844R',
 '15349V',
 '23819C',
 '12516Z',
 '25454Y',
 '12964A',
 '11881R',
 '26146S',
 '21433W',
 '12515X',
 '21494Q',
 '22746W',
 '11247T',
 '23851Y',
 '12816L',
 '13383L',
 '10552T',
 '13573Q',
 '15212U',
 '15267T',
 '19429N',
 '16954R',
 '13686D',
 '22736T',
 '16783Q',
 '15102N',
 '23799W',
 '13704F',
 '23342D',
 '20689A',
 '23500V',
 '18395R',
 '11866V',
 '10020M',
 '24763G',
 '11225J',
 '18871X',
 '17757U',
 '16390X',
 '24989G',
 '10699X',
 '15271K',
 '14964K',
 '23436M',
 '18498B',
 '21150K',
 '10961K',
 '11139Q',
 '25388L',
 '12560C',
 '24318L',
 '18886K',
 '14814R',
 '24634V',
 '23838G',
 '14257L',
 '22920M',
 '17533Y',
 '13477U',
 '13632G',
 '24377B',
 '17688B',
 '22348K',
 '22832P',
 '12069A',
 '12457J',
 '14390N',
 '10794R',
 '20682M',
 '11560X',
 '17022Z',
 '12895H',
 '19059G',
 '16128K',
 '11690K',
 '14194N',
 '24116Z',
 '24396F',
 '22078H',
 '11153K',
 '16463Y',
 '10849Q',
 '13767D',
 '19673Y',
 '16353R',
 '14133T',
 '22877L',
 '13563N',
 '14817X',
 '13398Y',
 '21897M',
 '11049P',
 '16411F',
 '17409X',
 '13702B',
 '15075K',
 '23312U',
 '23287V',
 '11221B',
 '10114V',
 '10245K',
 '11542V',
 '13586Z',
 '11600J',
 '15132W',
 '14909C',
 '21534C',
 '11815E',
 '16118H',
 '22430V',
 '24911V',
 '10503G',
 '22312P',
 '21842N',
 '24777R',
 '23615M',
 '15690E',
 '22961A',
 '14241W',
 '24080E',
 '20349C',
 '15617U',
 '11968D',
 '10372R',
 '10031R',
 '22325Y',
 '10211T',
 '10469G',
 '24438V',
 '12599D',
 '10806Y',
 '13780V',
 '25943N',
 '13947F',
 '20102U',
 '17476M',
 '12696B',
 '21467N',
 '18960W',
 '17414Q',
 '20738N',
 '17041D',
 '20818L',
 '13866F',
 '20792T',
 '23108V',
 '21461B',
 '10679R',
 '10096T',
 '15140V',
 '11181P',
 '12273Z',
 '13542F',
 '25381X',
 '24213X',
 '11828N',
 '24431H',
 '24480U',
 '13404T',
 '18633H',
 '17952S',
 '13517G',
 '20245Q',
 '22720E',
 '24348U',
 '22914R',
 '24652X',
 '13065X',
 '25762J',
 '24699X',
 '10507O',
 '11267Z',
 '17696A',
 '15224B',
 '14754Z',
 '20519B',
 '12294H',
 '23123R',
 '16546C',
 '11099E']

In [9]:
base_dir = '2026-08-08_preprocess'

template = '''\
#!/bin/bash -l
#$ -N {job_name}
#$ -P batmanlab
#$ -pe omp 4
#$ -l gpus=1
#$ -l gpu_memory=16G
#$ -l h_rt=12:00:00
set -eo pipefail

mamba activate $PROJECT/mambaforge/envs/warp

export PYTHONPATH=$LP_ROOT:$PROJECT:$PYTHOPATH

python $LP_ROOT/scripts/preprocess.py {config} \\
    --set dataset.name={data_name} \\
    --set dataset.root={data_root} \\
    --set dataset.examples.subjects=[{subject}] \\
    --set dataset.examples.variant={variant} \\

'''
name_format = 'job{params_hash}'

grid = ps.param_grid(
    config='2026-08-08_config.yaml',
    data_name='COPDGene',
    data_root=str(data_root),
    subject=subject_list,
    variant='2026-08-08'
)
len(grid)

1000

In [10]:
%autoreload
try:
    jobs = ps.setup(base_dir, template, name_format, grid, overwrite=False)
except OSError:
    jobs = ps.load(base_dir)

jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.subject,params.variant,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime
0,jobb5f34bb3ee104fea,RUNNING,1,7144818,scc-307,00:00:16,Loading /restricted/projectnb/batmanlab/mragoz...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,16514P,2026-08-08,NaN,2026-08-11T22:30:47,status,None,None,False,None,None
1,job592ea5b621a54700,RUNNING,1,7144819,scc-j07,00:00:16,Loading /restricted/projectnb/batmanlab/mragoz...,Total optimization time: 13.7626s\n\nRunning s...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,20748Q,2026-08-08,NaN,2026-08-11T22:30:47,status,None,None,False,None,None
2,job4ce868ed0e3b2485,RUNNING,1,7144820,scc-j07,00:00:16,Loading /restricted/projectnb/batmanlab/mragoz...,\nRunning sliver perturbation...\nLegend of th...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,11007Z,2026-08-08,NaN,2026-08-11T22:30:47,status,None,None,False,None,None
3,job2536956436071621,RUNNING,1,7144821,scc-j07,00:00:16,Loading /restricted/projectnb/batmanlab/mragoz...,Total optimization time: 10.589s\n\nRunning sl...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,14771Z,2026-08-08,NaN,2026-08-11T22:30:47,status,None,None,False,None,None
4,jobe2fe1b602d1ab0c6,RUNNING,1,7144822,scc-215,00:00:16,Loading /restricted/projectnb/batmanlab/mragoz...,Total optimization time: 11.3248s\n\nRunning s...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,13651K,2026-08-08,NaN,2026-08-11T22:30:47,status,None,None,False,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,jobad976677102cebf9,RECOVERED,1,7145823,None,None,INFO: /restricted/projectnb/batmanlab/mragoza/...,"File ""/projectnb/batmanlab/mragoza/lung-proj...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,20519B,2026-08-08,NaN,None,None,None,None,False,None,None
996,job60e111a5f43e1752,RECOVERED,1,7145824,None,None,Loading /restricted/projectnb/batmanlab/mragoz...,Total optimization time: 20.4356s\n\nRunning s...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,12294H,2026-08-08,NaN,None,None,None,None,False,None,None
997,jobcfd159863ee1c7f4,RECOVERED,1,7145825,None,None,Loading /restricted/projectnb/batmanlab/mragoz...,Total optimization time: 18.7251s\n\nRunning s...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,23123R,2026-08-08,NaN,None,None,None,None,False,None,None
998,jobb993cdf66950d0c5,RECOVERED,1,7145826,None,None,Loading /restricted/projectnb/batmanlab/mragoz...,\nRunning sliver perturbation...\nLegend of th...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,16546C,2026-08-08,NaN,None,None,None,None,False,None,None
999,jobc165ccd080946255,RECOVERED,1,7145827,None,None,Loading /restricted/projectnb/batmanlab/mragoz...,Total optimization time: 20.906s\n\nRunning sl...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,11099E,2026-08-08,NaN,None,None,None,None,False,None,None

In [11]:
%autoreload
jobs = ps.recover(jobs)
jobs = ps.status(jobs)
jobs = ps.history(jobs)
jobs = ps.collect(jobs)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.subject,params.variant,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime
0,jobb5f34bb3ee104fea,RUNNING,1,7144818,scc-307,00:00:16,Loading /restricted/projectnb/batmanlab/mragoz...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,16514P,2026-08-08,NaN,2026-08-11T22:30:47,status,None,None,False,<NA>,<NA>
1,job592ea5b621a54700,RUNNING,1,7144819,scc-j07,00:00:16,Loading /restricted/projectnb/batmanlab/mragoz...,Total optimization time: 13.7626s\n\nRunning s...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,20748Q,2026-08-08,NaN,2026-08-11T22:30:47,status,None,None,False,<NA>,<NA>
2,job4ce868ed0e3b2485,RUNNING,1,7144820,scc-j07,00:00:16,Loading /restricted/projectnb/batmanlab/mragoz...,\nRunning sliver perturbation...\nLegend of th...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,11007Z,2026-08-08,NaN,2026-08-11T22:30:47,status,None,None,False,<NA>,<NA>
3,job2536956436071621,RUNNING,1,7144821,scc-j07,00:00:16,Loading /restricted/projectnb/batmanlab/mragoz...,Total optimization time: 10.589s\n\nRunning sl...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,14771Z,2026-08-08,NaN,2026-08-11T22:30:47,status,None,None,False,<NA>,<NA>
4,jobe2fe1b602d1ab0c6,RUNNING,1,7144822,scc-215,00:00:16,Loading /restricted/projectnb/batmanlab/mragoz...,Total optimization time: 11.3248s\n\nRunning s...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,13651K,2026-08-08,NaN,2026-08-11T22:30:47,status,None,None,False,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,jobad976677102cebf9,RECOVERED,1,7145823,None,None,INFO: /restricted/projectnb/batmanlab/mragoza/...,"File ""/projectnb/batmanlab/mragoza/lung-proj...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,20519B,2026-08-08,NaN,None,None,None,None,False,<NA>,<NA>
996,job60e111a5f43e1752,RECOVERED,1,7145824,None,None,Loading /restricted/projectnb/batmanlab/mragoz...,Total optimization time: 20.4356s\n\nRunning s...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,12294H,2026-08-08,NaN,None,None,None,None,False,<NA>,<NA>
997,jobcfd159863ee1c7f4,RECOVERED,1,7145825,None,None,Loading /restricted/projectnb/batmanlab/mragoz...,Total optimization time: 18.7251s\n\nRunning s...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,23123R,2026-08-08,NaN,None,None,None,None,False,<NA>,<NA>
998,jobb993cdf66950d0c5,RECOVERED,1,7145826,None,None,Loading /restricted/projectnb/batmanlab/mragoz...,\nRunning sliver perturbation...\nLegend of th...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,16546C,2026-08-08,NaN,None,None,None,None,False,<NA>,<NA>
999,jobc165ccd080946255,RECOVERED,1,7145827,None,None,Loading /restricted/projectnb/batmanlab/mragoz...,Total optimization time: 20.906s\n\nRunning sl...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,11099E,2026-08-08,NaN,None,None,None,None,False,<NA>,<NA>

In [12]:
jobs.groupby('job_state').count()

,job_name,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,script_path,...,params.subject,params.variant,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime
job_state,,,,,,,,,,,,,,,,,,,,,
RECOVERED,976,976,976,0,0,976,976,976,976,976,...,976,976,0,0,0,0,0,976,0,0
RUNNING,24,24,24,24,24,24,24,24,24,24,...,24,24,0,24,24,0,0,24,0,0

In [77]:
# classify error messages
for j, row in jobs.iterrows():
    if pd.isnull(row.stderr):
        print(f'{j}: No stderr file')
    elif not str(row.stderr).strip():
        print(f'{j}: No error message')
    elif 'Non-positive density' in row.stderr:
        print(f'{j}: Non-positive density')
    elif 'CUDA out of memory' in row.stderr or ('Failed to allocate' in row.stderr and 'bytes on device \'cuda' in row.stderr):
        print(f'{j}: GPU out of memory')
    elif 'Exuding' in row.stderr or ('Moving #' in row.stderr and 'addr:' in row.stderr):
        print(f'{j}: pygalmesh output')
    else:
        print(f'{j}: Uncategorized')
        raise RuntimeError(f'Uncategorized stderr for job index {j}:\n{row.stderr}')

0: No error message
1: pygalmesh output
2: pygalmesh output
3: pygalmesh output
4: pygalmesh output
5: pygalmesh output
6: pygalmesh output
7: pygalmesh output
8: pygalmesh output
9: pygalmesh output
10: pygalmesh output
11: pygalmesh output
12: pygalmesh output
13: pygalmesh output
14: pygalmesh output
15: pygalmesh output
16: pygalmesh output
17: pygalmesh output
18: pygalmesh output
19: pygalmesh output
20: pygalmesh output
21: pygalmesh output
22: GPU out of memory
23: pygalmesh output
24: pygalmesh output
25: pygalmesh output
26: pygalmesh output
27: pygalmesh output
28: pygalmesh output
29: GPU out of memory
30: pygalmesh output
31: pygalmesh output
32: pygalmesh output
33: pygalmesh output
34: pygalmesh output
35: pygalmesh output
36: pygalmesh output
37: pygalmesh output
38: pygalmesh output
39: pygalmesh output
40: pygalmesh output
41: pygalmesh output
42: pygalmesh output
43: GPU out of memory
44: pygalmesh output
45: pygalmesh output
46: pygalmesh output
47: pygalmesh output
48: pygalmesh output
49: pygalmesh output
50: pygalmesh output
51: pygalmesh output
52: pygalmesh output
53: pygalmesh output
54: GPU out of memory
55: GPU out of memory
56: pygalmesh output
57: pygalmesh output
58: pygalmesh output
59: GPU out of memory
60: pygalmesh output
61: pygalmesh output
62: pygalmesh output
63: pygalmesh output
64: pygalmesh output
65: GPU out of memory
66: pygalmesh output
67: pygalmesh output
68: pygalmesh output
69: pygalmesh output
70: GPU out of memory
71: pygalmesh output
72: GPU out of memory
73: pygalmesh output
74: pygalmesh output
75: pygalmesh output
76: pygalmesh output
77: pygalmesh output
78: pygalmesh output
79: pygalmesh output
80: pygalmesh output
81: pygalmesh output
82: pygalmesh output
83: pygalmesh output
84: pygalmesh output
85: pygalmesh output
86: GPU out of memory
87: GPU out of memory
88: pygalmesh output
89: pygalmesh output
90: GPU out of memory
91: pygalmesh output
92: pygalmesh output
93: pygalmesh output
94: pygalmesh output
95: pygalmesh output
96: pygalmesh output
97: pygalmesh output
98: pygalmesh output
99: pygalmesh output
100: pygalmesh output
101: pygalmesh output
102: pygalmesh output
103: pygalmesh output
104: pygalmesh output
105: pygalmesh output
106: pygalmesh output
107: pygalmesh output
108: GPU out of memory
109: GPU out of memory
110: pygalmesh output
111: pygalmesh output
112: pygalmesh output
113: pygalmesh output
114: pygalmesh output
115: GPU out of memory
116: pygalmesh output
117: pygalmesh output
118: pygalmesh output
119: pygalmesh output
120: pygalmesh output
121: pygalmesh output
122: pygalmesh output
123: pygalmesh output
124: pygalmesh output
125: pygalmesh output
126: pygalmesh output
127: GPU out of memory
128: pygalmesh output
129: pygalmesh output
130: pygalmesh output
131: pygalmesh output
132: pygalmesh output
133: pygalmesh output
134: pygalmesh output
135: pygalmesh output
136: pygalmesh output
137: pygalmesh output
138: pygalmesh output
139: pygalmesh output
140: pygalmesh output
141: pygalmesh output
142: pygalmesh output
143: GPU out of memory
144: pygalmesh output
145: pygalmesh output
146: pygalmesh output
147: pygalmesh output
148: pygalmesh output
149: pygalmesh output
150: pygalmesh output
151: GPU out of memory
152: pygalmesh output
153: pygalmesh output
154: pygalmesh output
155: pygalmesh output
156: pygalmesh output
157: pygalmesh output
158: pygalmesh output
159: pygalmesh output
160: GPU out of memory
161: pygalmesh output
162: pygalmesh output
163: pygalmesh output
164: pygalmesh output
165: pygalmesh output
166: pygalmesh output
167: pygalmesh output
168: pygalmesh output
169: pygalmesh output
170: pygalmesh output
171: pygalmesh output
172: pygalmesh output
173: GPU out of memory
174: pygalmesh output
175: GPU out of memory
176: pygalmesh output
177: pygalmesh output
178: pygalmesh output
179: pygalmesh output
180: pygalmesh output
181: pygalmesh output
182: GPU out of memory
183: pygalmesh output
184: pygalmesh output
185: pygalmesh output
186: GPU out of memory
187: pygalmesh output
188: pygalmesh output
189: pygalmesh output
190: pygalmesh output
191: pygalmesh output
192: pygalmesh output
193: pygalmesh output
194: GPU out of memory
195: pygalmesh output
196: pygalmesh output
197: pygalmesh output
198: pygalmesh output
199: pygalmesh output
200: pygalmesh output
201: pygalmesh output
202: pygalmesh output
203: pygalmesh output
204: pygalmesh output
205: GPU out of memory
206: pygalmesh output
207: pygalmesh output
208: pygalmesh output
209: pygalmesh output
210: pygalmesh output
211: pygalmesh output
212: pygalmesh output
213: pygalmesh output
214: pygalmesh output
215: pygalmesh output
216: pygalmesh output
217: pygalmesh output
218: pygalmesh output
219: pygalmesh output
220: pygalmesh output
221: pygalmesh output
222: No stderr file
223: No stderr file
224: No stderr file
225: No stderr file
226: No stderr file
227: No stderr file
228: No stderr file
229: No stderr file
230: No stderr file
231: No stderr file
232: No stderr file
233: No stderr file
234: No stderr file
235: No stderr file
236: No stderr file
237: No stderr file
238: No stderr file
239: No stderr file
240: No stderr file
241: No stderr file
242: No stderr file
243: No stderr file
244: No stderr file
245: No stderr file
246: No stderr file
247: No stderr file
248: No stderr file
249: No stderr file
250: No stderr file
251: No stderr file
252: No stderr file
253: No stderr file
254: No stderr file
255: No stderr file
256: No stderr file
257: No stderr file
258: No stderr file
259: No stderr file
260: No stderr file
261: No stderr file
262: No stderr file
263: No stderr file
264: No stderr file
265: No stderr file
266: No stderr file
267: No stderr file
268: No stderr file
269: No stderr file
270: No stderr file
271: No stderr file
272: No stderr file
273: No stderr file
274: No stderr file
275: No stderr file
276: No stderr file
277: No stderr file
278: No stderr file
279: No stderr file
280: No stderr file
281: No stderr file
282: No stderr file
283: No stderr file
284: No stderr file
285: No stderr file
286: No stderr file
287: No stderr file
288: No stderr file
289: No stderr file
290: No stderr file
291: No stderr file
292: No stderr file
293: No stderr file
294: No stderr file
295: No stderr file
296: No stderr file
297: No stderr file
298: No stderr file
299: No stderr file
300: No stderr file
301: No stderr file
302: No stderr file
303: No stderr file
304: No stderr file
305: No stderr file
306: No stderr file
307: No stderr file
308: No stderr file
309: No stderr file
310: No stderr file
311: No stderr file
312: No stderr file
313: No stderr file
314: No stderr file
315: No stderr file
316: No stderr file
317: No stderr file
318: No stderr file
319: No stderr file
320: No stderr file
321: No stderr file
322: No stderr file
323: No stderr file
324: No stderr file
325: No stderr file
326: No stderr file
327: No stderr file
328: No stderr file
329: No stderr file
330: No stderr file
331: No stderr file
332: No stderr file
333: No stderr file
334: No stderr file
335: No stderr file
336: No stderr file
337: No stderr file
338: No stderr file
339: No stderr file
340: No stderr file
341: No stderr file
342: No stderr file
343: No stderr file
344: No stderr file
345: No stderr file
346: No stderr file
347: No stderr file
348: No stderr file
349: No stderr file
350: No stderr file
351: No stderr file
352: No stderr file
353: No stderr file
354: No stderr file
355: No stderr file
356: No stderr file
357: No stderr file
358: No stderr file
359: No stderr file
360: No stderr file
361: No stderr file
362: No stderr file
363: No stderr file
364: No stderr file
365: No stderr file
366: No stderr file
367: No stderr file
368: No stderr file
369: No stderr file
370: No stderr file
371: No stderr file
372: No stderr file
373: No stderr file
374: No stderr file
375: No stderr file
376: No stderr file
377: No stderr file
378: No stderr file
379: No stderr file
380: No stderr file
381: No stderr file
382: No stderr file
383: No stderr file
384: No stderr file
385: No stderr file
386: No stderr file
387: No stderr file
388: No stderr file
389: No stderr file
390: No stderr file
391: No stderr file
392: No stderr file
393: No stderr file
394: No stderr file
395: No stderr file
396: No stderr file
397: No stderr file
398: No stderr file
399: No stderr file
400: No stderr file
401: No stderr file
402: No stderr file
403: No stderr file
404: No stderr file
405: No stderr file
406: No stderr file
407: No stderr file
408: No stderr file
409: No stderr file
410: No stderr file
411: No stderr file
412: No stderr file
413: No stderr file
414: No stderr file
415: No stderr file
416: No stderr file
417: No stderr file
418: No stderr file
419: No stderr file
420: No stderr file
421: No stderr file
422: No stderr file
423: No stderr file
424: No stderr file
425: No stderr file
426: No stderr file
427: No stderr file
428: No stderr file
429: No stderr file
430: No stderr file
431: No stderr file
432: No stderr file
433: No stderr file
434: No stderr file
435: No stderr file
436: No stderr file
437: No stderr file
438: No stderr file
439: No stderr file
440: No stderr file
441: No stderr file
442: No stderr file
443: No stderr file
444: No stderr file
445: No stderr file
446: No stderr file
447: No stderr file
448: No stderr file
449: No stderr file
450: No stderr file
451: No stderr file
452: No stderr file
453: No stderr file
454: No stderr file
455: No stderr file
456: No stderr file
457: No stderr file
458: No stderr file
459: No stderr file
460: No stderr file
461: No stderr file
462: No stderr file
463: No stderr file
464: No stderr file
465: No stderr file
466: No stderr file
467: No stderr file
468: No stderr file
469: No stderr file
470: No stderr file
471: No stderr file
472: No stderr file
473: No stderr file
474: No stderr file
475: No stderr file
476: No stderr file
477: No stderr file
478: No stderr file
479: No stderr file
480: No stderr file
481: No stderr file
482: No stderr file
483: No stderr file
484: No stderr file
485: No stderr file
486: No stderr file
487: No stderr file
488: No stderr file
489: No stderr file
490: No stderr file
491: No stderr file
492: No stderr file
493: No stderr file
494: No stderr file
495: No stderr file
496: No stderr file
497: No stderr file
498: No stderr file
499: No stderr file
500: No stderr file
501: No stderr file
502: No stderr file
503: No stderr file
504: No stderr file
505: No stderr file
506: No stderr file
507: No stderr file
508: No stderr file
509: No stderr file
510: No stderr file
511: No stderr file
512: No stderr file
513: No stderr file
514: No stderr file
515: No stderr file
516: No stderr file
517: No stderr file
518: No stderr file
519: No stderr file
520: No stderr file
521: No stderr file
522: No stderr file
523: No stderr file
524: No stderr file
525: No stderr file
526: No stderr file
527: No stderr file
528: No stderr file
529: No stderr file
530: No stderr file
531: No stderr file
532: No stderr file
533: No stderr file
534: No stderr file
535: No stderr file
536: No stderr file
537: No stderr file
538: No stderr file
539: No stderr file
540: No stderr file
541: No stderr file
542: No stderr file
543: No stderr file
544: No stderr file
545: No stderr file
546: No stderr file
547: No stderr file
548: No stderr file
549: No stderr file
550: No stderr file
551: No stderr file
552: No stderr file
553: No stderr file
554: No stderr file
555: No stderr file
556: No stderr file
557: No stderr file
558: No stderr file
559: No stderr file
560: No stderr file
561: No stderr file
562: No stderr file
563: No stderr file
564: No stderr file
565: No stderr file
566: No stderr file
567: No stderr file
568: No stderr file
569: No stderr file
570: No stderr file
571: No stderr file
572: No stderr file
573: No stderr file
574: No stderr file
575: No stderr file
576: No stderr file
577: No stderr file
578: No stderr file
579: No stderr file
580: No stderr file
581: No stderr file
582: No stderr file
583: No stderr file
584: No stderr file
585: No stderr file
586: No stderr file
587: No stderr file
588: No stderr file
589: No stderr file
590: No stderr file
591: No stderr file
592: No stderr file
593: No stderr file
594: No stderr file
595: No stderr file
596: No stderr file
597: No stderr file
598: No stderr file
599: No stderr file
600: No stderr file
601: No stderr file
602: No stderr file
603: No stderr file
604: No stderr file
605: No stderr file
606: No stderr file
607: No stderr file
608: No stderr file
609: No stderr file
610: No stderr file
611: No stderr file
612: No stderr file
613: No stderr file
614: No stderr file
615: No stderr file
616: No stderr file
617: No stderr file
618: No stderr file
619: No stderr file
620: No stderr file
621: No stderr file
622: No stderr file
623: No stderr file
624: No stderr file
625: No stderr file
626: No stderr file
627: No stderr file
628: No stderr file
629: No stderr file
630: No stderr file
631: No stderr file
632: No stderr file
633: No stderr file
634: No stderr file
635: No stderr file
636: No stderr file
637: No stderr file
638: No stderr file
639: No stderr file
640: No stderr file
641: No stderr file
642: No stderr file
643: No stderr file
644: No stderr file
645: No stderr file
646: No stderr file
647: No stderr file
648: No stderr file
649: No stderr file
650: No stderr file
651: No stderr file
652: No stderr file
653: No stderr file
654: No stderr file
655: No stderr file
656: No stderr file
657: No stderr file
658: No stderr file
659: No stderr file
660: No stderr file
661: No stderr file
662: No stderr file
663: No stderr file
664: No stderr file
665: No stderr file
666: No stderr file
667: No stderr file
668: No stderr file
669: No stderr file
670: No stderr file
671: No stderr file
672: No stderr file
673: No stderr file
674: No stderr file
675: No stderr file
676: No stderr file
677: No stderr file
678: No stderr file
679: No stderr file
680: No stderr file
681: No stderr file
682: No stderr file
683: No stderr file
684: No stderr file
685: No stderr file
686: No stderr file
687: No stderr file
688: No stderr file
689: No stderr file
690: No stderr file
691: No stderr file
692: No stderr file
693: No stderr file
694: No stderr file
695: No stderr file
696: No stderr file
697: No stderr file
698: No stderr file
699: No stderr file
700: No stderr file
701: No stderr file
702: No stderr file
703: No stderr file
704: No stderr file
705: No stderr file
706: No stderr file
707: No stderr file
708: No stderr file
709: No stderr file
710: No stderr file
711: No stderr file
712: No stderr file
713: No stderr file
714: No stderr file
715: No stderr file
716: No stderr file
717: No stderr file
718: No stderr file
719: No stderr file
720: No stderr file
721: No stderr file
722: No stderr file
723: No stderr file
724: No stderr file
725: No stderr file
726: No stderr file
727: No stderr file
728: No stderr file
729: No stderr file
730: No stderr file
731: No stderr file
732: No stderr file
733: No stderr file
734: No stderr file
735: No stderr file
736: No stderr file
737: No stderr file
738: No stderr file
739: No stderr file
740: No stderr file
741: No stderr file
742: No stderr file
743: No stderr file
744: No stderr file
745: No stderr file
746: No stderr file
747: No stderr file
748: No stderr file
749: No stderr file
750: No stderr file
751: No stderr file
752: No stderr file
753: No stderr file
754: No stderr file
755: No stderr file
756: No stderr file
757: No stderr file
758: No stderr file
759: No stderr file
760: No stderr file
761: No stderr file
762: No stderr file
763: No stderr file
764: No stderr file
765: No stderr file
766: No stderr file
767: No stderr file
768: No stderr file
769: No stderr file
770: No stderr file
771: No stderr file
772: No stderr file
773: No stderr file
774: No stderr file
775: No stderr file
776: No stderr file
777: No stderr file
778: No stderr file
779: No stderr file
780: No stderr file
781: No stderr file
782: No stderr file
783: No stderr file
784: No stderr file
785: No stderr file
786: No stderr file
787: No stderr file
788: No stderr file
789: No stderr file
790: No stderr file
791: No stderr file
792: No stderr file
793: No stderr file
794: No stderr file
795: No stderr file
796: No stderr file
797: No stderr file
798: No stderr file
799: No stderr file
800: No stderr file
801: No stderr file
802: No stderr file
803: No stderr file
804: No stderr file
805: No stderr file
806: No stderr file
807: No stderr file
808: No stderr file
809: No stderr file
810: No stderr file
811: No stderr file
812: No stderr file
813: No stderr file
814: No stderr file
815: No stderr file
816: No stderr file
817: No stderr file
818: No stderr file
819: No stderr file
820: No stderr file
821: No stderr file
822: No stderr file
823: No stderr file
824: No stderr file
825: No stderr file
826: No stderr file
827: No stderr file
828: No stderr file
829: No stderr file
830: No stderr file
831: No stderr file
832: No stderr file
833: No stderr file
834: No stderr file
835: No stderr file
836: No stderr file
837: No stderr file
838: No stderr file
839: No stderr file
840: No stderr file
841: No stderr file
842: No stderr file
843: No stderr file
844: No stderr file
845: No stderr file
846: No stderr file
847: No stderr file
848: No stderr file
849: No stderr file
850: No stderr file
851: No stderr file
852: No stderr file
853: No stderr file
854: No stderr file
855: No stderr file
856: No stderr file
857: No stderr file
858: No stderr file
859: No stderr file
860: No stderr file
861: No stderr file
862: No stderr file
863: No stderr file
864: No stderr file
865: No stderr file
866: No stderr file
867: No stderr file
868: No stderr file
869: No stderr file
870: No stderr file
871: No stderr file
872: No stderr file
873: No stderr file
874: No stderr file
875: No stderr file
876: No stderr file
877: No stderr file
878: No stderr file
879: No stderr file
880: No stderr file
881: No stderr file
882: No stderr file
883: No stderr file
884: No stderr file
885: No stderr file
886: No stderr file
887: No stderr file
888: No stderr file
889: No stderr file
890: No stderr file
891: No stderr file
892: No stderr file
893: No stderr file
894: No stderr file
895: No stderr file
896: No stderr file
897: No stderr file
898: No stderr file
899: No stderr file
900: No stderr file
901: No stderr file
902: No stderr file
903: No stderr file
904: No stderr file
905: No stderr file
906: No stderr file
907: No stderr file
908: No stderr file
909: No stderr file
910: No stderr file
911: No stderr file
912: No stderr file
913: No stderr file
914: No stderr file
915: No stderr file
916: No stderr file
917: No stderr file
918: No stderr file
919: No stderr file
920: No stderr file
921: No stderr file
922: No stderr file
923: No stderr file
924: No stderr file
925: No stderr file
926: No stderr file
927: No stderr file
928: No stderr file
929: No stderr file
930: No stderr file
931: No stderr file
932: No stderr file
933: No stderr file
934: No stderr file
935: No stderr file
936: No stderr file
937: No stderr file
938: No stderr file
939: No stderr file
940: No stderr file
941: No stderr file
942: No stderr file
943: No stderr file
944: No stderr file
945: No stderr file
946: No stderr file
947: No stderr file
948: No stderr file
949: No stderr file
950: No stderr file
951: No stderr file
952: No stderr file
953: No stderr file
954: No stderr file
955: No stderr file
956: No stderr file
957: No stderr file
958: No stderr file
959: No stderr file
960: No stderr file
961: No stderr file
962: No stderr file
963: No stderr file
964: No stderr file
965: No stderr file
966: No stderr file
967: No stderr file
968: No stderr file
969: No stderr file
970: No stderr file
971: No stderr file
972: No stderr file
973: No stderr file
974: No stderr file
975: No stderr file
976: No stderr file
977: No stderr file
978: No stderr file
979: No stderr file
980: No stderr file
981: No stderr file

In [52]:
print(jobs[jobs.stderr.notna()].iloc[65].stderr)

  File "/projectnb/batmanlab/mragoza/lung-project/project/physics/warp/solver.py", line 412, in assemble_jacobian
    J = wp.fem.integrate(
        ^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/mambaforge/envs/warp/lib/python3.11/site-packages/warp/_src/fem/integrate.py", line 2055, in integrate
    return _launch_integrate_kernel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/mambaforge/envs/warp/lib/python3.11/site-packages/warp/_src/fem/integrate.py", line 1751, in _launch_integrate_kernel
    local_result = cache.borrow_temporary(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/mambaforge/envs/warp/lib/python3.11/site-packages/warp/_src/fem/cache.py", line 674, in borrow_temporary
    Temporary(shape=shape, dtype=dtype, pinned=pinned, device=device, requires_grad=requires_grad)
  File "/projectnb/batmanlab/mragoza/mambaforge/envs/warp/lib/python3.11/site-packages/warp/_src/types.py", line 3285, in __init__
    self._init_new(dtype, shape, strides, device, pinned)
  File "/projectnb/batmanlab/mragoza/mambaforge/envs/warp/lib/python3.11/site-packages/warp/_src/types.py", line 3741, in _init_new
    ptr = allocator.allocate(capacity)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/mambaforge/envs/warp/lib/python3.11/site-packages/warp/_src/context.py", line 4251, in allocate
    raise RuntimeError(f"Failed to allocate {size_in_bytes} bytes on device '{self.device}'")
RuntimeError: Failed to allocate 3090932460 bytes on device 'cuda:0'

In [25]:
jobs.loc[:, 'job_id'] = pd.NA

In [8]:
%autoreload
jobs = ps.submit(jobs)
jobs

NameError: name 'requires_id' is not defined